default: &default
  adapter: postgresql
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS")  { 5 } %>
  host:     <%= ENV.fetch("DATABASE_HOST")      { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME")  { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD")  { 'password' } %>

development:
  <<: *default
  database: minesweeper_rails_dev

test:
  <<: *default
  database: minesweeper_rails_test

production:
  <<: *default
  host:     <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
